version: '3'
services:
  db:
    image: mysql:5.7
    container_name: ${NAME}_sql
    volumes:
      - $PWD/mysql:/var/lib/mysql
      - $PWD/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    stdin_open: true
    tty: true
  web:
    build: './'
    container_name: ${NAME}_web
    depends_on:
      - db
    volumes:
      - ${PROJECT_FOLDER}/${NAME}:/var/www/html
      - $PWD/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${NAME}_phpmyadmin
    links:
      - db:db
    ports:
      - "8082:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PHP_UPLOAD_MAX_FILESIZE=5000MB
  adminer:
    image: adminer:latest
    container_name: ${NAME}_adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"
    volumes:
      - ~/adminer:/var/www/html
    
